### ISSUE TITLE
Possible deadline extension ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw6#13]
Hi,

I just realized that the coursework was released 2 days later than scheduled.
Does this mean there can be a possibility of a deadline extension, @m8pple  ?

**Comment by m8pple** [comment]
I'm afraid not, or at least it is not a valid reason for an extension.

This was something I mentioned in the lecture on Fri - previous cohorts have said
they preferred to have some down-time between one coursework ending and the
next being issued, so having the weekend free (at least of HPCE stuff) gives space
for other things (sleep, sports, socialising, revision, other courseworks...). Everyone
seemed quite happy with that (or at least, there were no strong objections).

So the intended hand-out date was 9:00 on Mon, rather than 22:00 on Friday - the
original timetable graphic was a bit sloppy there.

Umm, you're also not really supporting the argument with:
> I _just realized_ that the coursework was released 2 days later than scheduled.

**Comment by m8pple** [comment]
(This isn't directly to @malharjajoo, more a general observation on the same theme).

BTW, while we're on the topic, some others have asked about the possibility of
extensions due to conflict with exams. That is something that in principle is
doable, but it has to:
- be done with the consultation and agreement of all students.
- happen _well_ before the deadline (we're rapidly approaching the point
   where I'd be very uncomfortable changing it).
- not penalise anyone who starts early, nor reward those who started late.
If there is a genuine problem then it usually crops up and is dealt with
earlier, but I don't see any real reason for changing this one.

Students across all cohorts and departments are in quite a similar situation with
respect to exams and/or courseworks at the moment, which is why this year
cw6 was extended to operate over a longer period than previous years. That
gives plenty of flexibility about when to do it, 

Bear in mind that a lot of students actually really dislike deadlines changing
(for a wide variety of reasons) but are often not as vocal about it (they are
not going to to agitate for things to stay the same), so previously students
have often decided not to move back deadlines.
