### ISSUE TITLE
questions regarding min(1,exp(-g/t))*log2(n)

### ISSUE THREAD

**Issue by aaronlws95** [HPCE/hpce-2017-cw6#19]
Hi, isn't exp(-g/t) always going to be less than 1 as long as g/t is positive. Why is the min necessary? Also in the code: 
![capture](https://user-images.githubusercontent.com/9619150/33501160-76f9f0ec-d6d3-11e7-8a01-b65fbb2fdfb7.PNG)
I noticed that g/t is less than 1 most of the time so it never does the exponential.

**Comment by malharjajoo** [comment]
This might not answer your question ( but might indirectly answer your question about "why is min necessary" ) but I think that the metric in the readme.md might not be always true.

For example if `r = g/t = 0.9 `, then the code output will be `1*log2(n)` while the metric suggests `exp(-r)*log2(n)`

**Comment by nicholzk** [comment]
I believe that the code intends to impose a penalty of exp(-g/t) for programs that exceed the time budget on the score ( g/t > 1), else score is simply log2(n). The mathematical formulation is certainly wrong, but I am not sure if there is a simple way to express this logic.

**Comment by m8pple** [comment]
My intention was as stated by @nicholzk says:
- The score is log2(n) if within budget.
- The score is log2(n) * exp(-g/t) if the budget is exceeded.

So the cost function I was expecting was something like this:
![image](https://user-images.githubusercontent.com/3024705/33564002-595611a2-d911-11e7-84fe-9d215042256b.png)

So there is quite a big penalty for going over the time budget, with a bit of
a cliff, but still some reward. Originally I had min(1,exp(-g/t)/exp(-1)), but
then decided to penalise exceeding the budget a bit more - as @nichlzk says,
there isn't an elegant way of expressing that, and I seem not to have noticed
that the maths no longer follows the function.

Regardig @aaronlws95's point about g/t being less than 1 most of the time: that is because
the default prediction of `n` is extremely conservative. You'll want to try to make a better
prediction of `n`, so that you can get reasonably close to the g/t=1
