### ISSUE TITLE
Reflection.md word limit?

### ISSUE THREAD

**Issue by dc3315** [HPCE/hpce-2017-cw6#42]
A friend and I don't understand the word limitations for the reflection.md.

The paragraph guidances states that the limit for the component is 1000 words,
yet there are ten questions where the limit is 50 words,  making the maximum number of words 500. So presumably we follow the 500 words limit, right?

Many thanks.

**Comment by adamsolomou** [comment]
Adding to that, is there a strict enforcement on the 50 word limit? If we need 5-10 more words to give a concrete answer is that ok? 

Thanks!

**Comment by m8pple** [comment]
Yes, you're correct - it should be 500 words. Originally it was a bit longer with
more sections, but on reflection (ho-ho) it was just adding overhead that wasn't needed.

The 50 word limit is mainly to limit the amount that students write, as otherwise there is
a tendency for people to keep writing more and more in the hopes that they will "hit"
the "correct" answer, but it usually just results in vagueness. It's much better to have a
very clear, short, and focussed answer, and 50 words means that people can usually
only say one thing.

However, the word limit is not especially strict - if someone has written 100 words for
every answer then there is a problem, but if one or two answers are a bit over it isn't
a problem. Things like URLS and other links can be treated as one word.
